language: node_js
node_js:
  - 0.10

addons:
  firefox: "25.0"

before_install:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'

before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'

notifications:
  email: false
  hipchat: b83791c5d4b712de736d8c1e9f7fb8@271266
